version: '3'
services:
    fpm:
        build: .
        command: /usr/sbin/php-fpm82 --allow-to-run-as-root -F -y /etc/php82/php-fpm.conf
        privileged: true
        ports:
            - '9000:9000'
        networks:
            - backend
    nginx:
      image: 'nginx:mainline-alpine'
      command: nginx -g 'daemon off;'
      ports:
          - '80:80'
      volumes:
          - './nginx.conf:/etc/nginx/nginx.conf'
      networks:
          - backend
      depends_on:
          - fpm
networks:
  backend:
        driver: bridge
